package io.github.youndie.razves.klib

import io.github.youndie.razves.read.ElfReader

/**
 * The symbols a static archive defines, out of its own index.
 *
 * This is the answer to the one part of a binary no mangling scheme can explain. 26.7% of the
 * attributed bytes of a real release binary carry names with no scheme at all — `ossl_aes_gcm_*`,
 * `nid_objs`, `sha1_multi_block` — because the C ABI has no namespaces. A grammar over names cannot
 * recover where they came from; the archive that defines them can, and the archives are right there:
 * a cinterop klib carries them at the `included` directory under `default/targets/<target>`, and
 * `cryptography-provider-openssl3-prebuilt` ships a 12,737,852-byte `libcrypto.a` that way.
 *
 * **The index, not the members.** A GNU `ar` writes a first member named `/` holding every symbol
 * its objects define, sorted, with an offset each. Reading it costs one pass over a few hundred
 * kilobytes; parsing every object file inside a 12 MB archive to learn the same thing would cost
 * thousands. `libcrypto.a` declares 9,023 symbols in 251,116 bytes of index.
 *
 * Refused rather than guessed at: the BSD variant (`__.SYMDEF`), and an archive with no index at
 * all. Both exist, neither appears in a Kotlin/Native link, and a reader that silently returns
 * nothing for them would make a library look weightless.
 */
internal object Archive {
    private val MAGIC = "!<arch>\n".encodeToByteArray()
    private const val MEMBER_HEADER_SIZE = 60
    private const val NAME_SIZE = 16
    private const val SIZE_AT = 48
    private const val SIZE_LENGTH = 10

    fun matches(data: ByteArray): Boolean = data.size >= MAGIC.size && MAGIC.indices.all { data[it] == MAGIC[it] }

    /**
     * Every symbol the members define, by reading each one.
     *
     * Fifty times the bytes of the index and the only way to reach what the index cannot name:
     * `libcrypto.a` is 12,737,852 bytes across 1,033 members against a 251,116-byte index, and
     * `nid_objs`, `k25519Precomp` and `param_group_list` are all in members and in none of the index.
     *
     * Fifty times the bytes is **not** fifty times the time, which is why this ended up on by default:
     * both modes inflate the archive out of the klib first, and that inflate dominates. Measured on
     * the `shildik` link classpath, warmed, 3,859 ms against 3,926 ms - and the bytes no archive
     * places fall from 4,572,896 to 955,215.
     *
     * One name it still cannot reach: `__unnamed_3673`, 142,096 bytes on the measured subject, is
     * generated by the linker for an anonymous object and is in no member at all. Nothing that
     * matches by name will ever place it.
     */
    fun definedSymbolsDeep(data: ByteArray): Set<String> {
        if (!matches(data)) return emptySet()
        val out = mutableSetOf<String>()
        var at = MAGIC.size
        while (at + MEMBER_HEADER_SIZE <= data.size) {
            val name = data.decodeToString(at, at + NAME_SIZE).trimEnd()
            val size = data.decodeToString(at + SIZE_AT, at + SIZE_AT + SIZE_LENGTH).trim().toLongOrNull() ?: break
            val body = at + MEMBER_HEADER_SIZE
            if (body + size > data.size) break
            // The special members are named exactly `/`, `//` and `/SYM64/`. A member called `/1234`
            // is an ordinary object whose name was too long for the sixteen-byte field and lives in
            // the long-name table - and skipping those on a "starts with a slash" test throws away
            // almost every member of a real archive, because `libcrypto-lib-aes-gcm-avx512.o` is
            // thirty characters. Measured: it left the deep read placing LESS than the index did.
            //
            // The names themselves are never resolved: the question is which ARCHIVE defines a
            // symbol, and every member of one archive is the same answer.
            if (name != "/" && name != "//" && name != "/SYM64/") {
                out += ElfReader.definedSymbolNames(data.copyOfRange(body, body + size.toInt()))
            }
            at = body + size.toInt() + (size.toInt() % 2)
        }
        return out
    }

    /** Every symbol the archive's index names, or an empty set when it has no index razves reads. */
    fun definedSymbols(data: ByteArray): Set<String> {
        if (!matches(data)) return emptySet()
        var at = MAGIC.size
        while (at + MEMBER_HEADER_SIZE <= data.size) {
            val name = data.decodeToString(at, at + NAME_SIZE).trimEnd()
            val size =
                data.decodeToString(at + SIZE_AT, at + SIZE_AT + SIZE_LENGTH).trim().toLongOrNull() ?: return emptySet()
            val body = at + MEMBER_HEADER_SIZE
            when {
                // GNU, 32-bit offsets. The common case and the one Kotlin/Native links.
                name == "/" -> return readIndex(data, body, size.toInt(), offsetBytes = 4)

                // GNU, 64-bit offsets: the same layout with wider numbers, used once an archive passes
                // four gigabytes of member offsets.
                name == "/SYM64/" -> return readIndex(data, body, size.toInt(), offsetBytes = 8)

                // `//` is the long-name table and always follows the index, so reaching it means there
                // was none. Anything else means the first member is an object: no index at all.
                name == "//" || !name.startsWith("/") -> return emptySet()
            }
            at = body + size.toInt() + (size.toInt() % 2)
        }
        return emptySet()
    }

    /**
     * The index: a count, that many offsets, then that many NUL-terminated names.
     *
     * Only the names are read. The offsets say which member defines each symbol, which would matter
     * to a linker and does not matter here: razves is asking which *archive* a symbol came from, and
     * every member of one archive is the same answer.
     */
    private fun readIndex(
        data: ByteArray,
        at: Int,
        size: Int,
        offsetBytes: Int,
    ): Set<String> {
        if (at + size > data.size || size < offsetBytes) return emptySet()
        val count = readBigEndian(data, at, offsetBytes).toInt()
        if (count <= 0) return emptySet()
        var cursor = at + offsetBytes + count * offsetBytes
        val end = at + size
        val out = LinkedHashSet<String>(count)
        repeat(count) {
            if (cursor >= end) return out
            var stop = cursor
            while (stop < end && data[stop].toInt() != 0) stop++
            out += data.decodeToString(cursor, stop)
            cursor = stop + 1
        }
        return out
    }

    /** Archive indexes are big-endian whatever the machine is: the format predates the argument. */
    private fun readBigEndian(
        data: ByteArray,
        at: Int,
        bytes: Int,
    ): Long {
        var value = 0L
        for (i in 0 until bytes) value = (value shl 8) or (data[at + i].toLong() and 0xFF)
        return value
    }
}
